name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure
        run: |
          cmake -B build `
            -DERGO_BUILD_TESTS=ON `
            -DERGO_AUDIO_BACKEND=dummy

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --build-config Release --output-on-failure
